repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format
    name: clang-format
    description: Format files with ClangFormat.
    language: system
    files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
    args: ['-fallback-style=none']
